_extends: .github
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ['Semantic Pull Request', 'Travis CI - Branch']
      enforce_admins: true
      restrictions: null
